# Generated by Django 3.2.25 on 2024-08-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='Student',
        ),
    ]
